{% set version = "4.20251130.1" %}

package:
  name: xdotool
  version: {{ version }}

source:
  url: https://github.com/jordansissel/xdotool/archive/v{{ version }}.tar.gz
  sha256: a9837efca5ceb2c04f1bd276985d93960c5ea11eed9725c517ae3ebc3fc6dca7

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - xorg-libx11
    - xorg-libxi
    - xorg-libxtst
    - xorg-libxinerama
    - xorg-xorgproto
    - libxkbcommon

test:
  commands:
    - 'xdotool --version'

about:
  home: https://github.com/jordansissel/xdotool
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: Fake keyboard/mouse input, window management, and more with X11
  dev_url: https://github.com/jordansissel/xdotool

extra:
  recipe-maintainers:
    - ehfd
